Training device: cuda:0
Create model: done
Traceback (most recent call last):
  File "/cluster/home/xudjian/ModalGNN_Time_Domain/train.py", line 186, in <module>
    train('config/config.yaml')
  File "/cluster/home/xudjian/ModalGNN_Time_Domain/train.py", line 56, in train
    dataloader_train = get_dataset(data_path=config['data']['path'], 
  File "/cluster/home/xudjian/ModalGNN_Time_Domain/data/dataset_loader.py", line 129, in get_dataset
    fft_abs = mat_contents['acceleration_fft_abs_out'][:, 0]
KeyError: 'acceleration_fft_abs_out'
